import sqlite3, json
from datetime import datetime

DB_PATH = 'data/celpip_practice.db'

answers = [
  {
    'id': 561,
    'answer': 'Balancing your child\'s screen use is a challenge many parents face today, and addressing it while they are still nine is far easier than trying to reverse deeply ingrained habits at thirteen. The most effective approach is to set clear, consistent limits: no screens before school, a fixed window of one hour of recreational use after homework is done, and a complete cutoff at least an hour before bedtime. Equally important is what replaces that time — children this age disengage from screens more willingly when they have appealing alternatives waiting, such as outdoor play, a creative hobby, or regular trips to the local library. When you take devices away and your child reacts with irritability, stay calm and consistent; giving in under pressure teaches them that persistence gets results, which reinforces the very habit you are trying to break. It helps to explain your reasoning in plain terms, because children as young as nine understand that too much screen time affects their focus and mood, and feeling respected in the conversation makes them more cooperative with the boundaries. Give the new routine at least two to three weeks before judging its effectiveness — adjustment takes time, and you will likely see their interest in other activities gradually return.',
    'vocab': [
      {'word': 'ingrained', 'definition': 'deeply fixed and difficult to change, especially as a habit or attitude', 'example': 'After years of working late, the habit was so ingrained that she struggled to leave the office on time.', 'type': 'adjective'},
      {'word': 'recreational', 'definition': 'done for enjoyment and relaxation rather than for work or obligation', 'example': 'The community centre offers recreational programs for children of all ages throughout the summer.', 'type': 'adjective'},
      {'word': 'disengage', 'definition': 'to stop being involved in or interested in something and move your attention elsewhere', 'example': 'It can be hard to disengage from a task when your phone keeps buzzing nearby.', 'type': 'verb'},
      {'word': 'reinforces', 'definition': 'strengthens or encourages a habit, belief, or behaviour by repeating or rewarding it', 'example': 'Giving a child extra screen time as a reward reinforces the idea that screens are the ultimate treat.', 'type': 'verb'},
      {'word': 'adjustment', 'definition': 'the process of gradually adapting to a new situation, rule, or set of conditions', 'example': 'Moving to a new school requires a period of adjustment before a child feels fully settled.', 'type': 'noun'}
    ]
  },
  {
    'id': 562,
    'answer': 'Phishing emails are specifically engineered to look authentic, and falling for one says nothing about your intelligence — it happens to careful, educated people every day. Your first priority is to file a report with your local police and with the Canadian Anti-Fraud Centre, because a case number is often required before the bank or any other institution will escalate their investigation. Contact your bank again in writing and formally dispute the transaction, citing that it was the result of fraud; keeping a detailed log of every communication — dates, names, and what was said — strengthens your position considerably if the case goes further. You should also place a fraud alert with both Equifax Canada and TransUnion Canada, which flags your credit file so that any lender attempting to extend credit in your name must take additional verification steps. Going forward, the most protective habit is to verify any urgent financial request by calling the institution directly, using the number on their official website rather than any link or number provided in the email. Most people who go through this become significantly more alert to these tactics, and that awareness itself is a meaningful form of protection.',
    'vocab': [
      {'word': 'phishing', 'definition': 'a fraudulent attempt to steal personal or financial information by pretending to be a trustworthy source, usually by email', 'example': 'She received a phishing email that looked exactly like a message from her bank, complete with the official logo.', 'type': 'noun'},
      {'word': 'dispute', 'definition': 'to formally challenge or contest a charge, claim, or decision you believe is incorrect or fraudulent', 'example': 'He called his credit card company to dispute a charge he had never authorized.', 'type': 'verb'},
      {'word': 'fraud alert', 'definition': 'a notice placed on a credit file that warns lenders to verify your identity before approving any new credit in your name', 'example': 'After her wallet was stolen, she placed a fraud alert on her file to prevent anyone from opening new accounts.', 'type': 'noun phrase'},
      {'word': 'verification', 'definition': 'the process of confirming that information, identity, or a claim is accurate and genuine', 'example': 'The bank requires two forms of identification for verification before releasing any funds.', 'type': 'noun'},
      {'word': 'escalate', 'definition': 'to move a matter to a higher level of authority or seriousness so that more significant action can be taken', 'example': 'When the first customer service agent could not help, she asked to escalate the complaint to a supervisor.', 'type': 'verb'}
    ]
  },
  {
    'id': 563,
    'answer': 'Your instinct to act is the right one, and while your child\'s fear of retaliation is completely understandable, staying silent rarely makes this kind of bullying stop on its own. Before taking any steps, document everything: take screenshots of every harmful message, note the dates, platforms, and usernames involved, because this evidence will be essential whether you approach the school or the police. Contact the school directly and ask to speak with the principal or a guidance counsellor — most Canadian schools have formal anti-bullying policies, and presenting your evidence calmly and thoroughly gives your complaint the credibility it needs to trigger a proper response. If any messages contain threats, sexual content, or are severe and repeated enough to constitute harassment, they may meet the threshold for a police report, which is worth pursuing even if it feels like a large step. At home, make sure your child knows that you are acting to protect them, not to embarrass them — involving them in decisions about next steps, where possible, gives them a sense of agency in a situation where they currently feel powerless. The changes in eating and school attendance you have noticed are serious signs of distress, and a school counsellor or therapist can offer your child a space to process what they are experiencing alongside whatever steps you take.',
    'vocab': [
      {'word': 'retaliation', 'definition': 'an action taken against someone in response to harm they caused, often making a situation worse', 'example': 'The student was afraid that reporting the bullying would lead to retaliation from the other kids.', 'type': 'noun'},
      {'word': 'document', 'definition': 'to record information carefully and systematically, usually to use as proof or reference later', 'example': 'It is important to document every incident in writing, including the date and the names of those involved.', 'type': 'verb'},
      {'word': 'guidance counsellor', 'definition': 'a trained professional in a school setting who supports students with emotional, social, and academic challenges', 'example': 'The guidance counsellor met with the student weekly to help her manage anxiety about exams.', 'type': 'noun phrase'},
      {'word': 'credibility', 'definition': 'the quality of being trusted and taken seriously by others, especially when making a complaint or claim', 'example': 'Bringing written evidence to the meeting gave her complaint far more credibility than a verbal account alone.', 'type': 'noun'},
      {'word': 'threshold', 'definition': 'the level or point at which something becomes serious enough to require a particular action or response', 'example': 'The lawyer explained that repeated threats by text message can meet the threshold for criminal harassment.', 'type': 'noun'},
      {'word': 'agency', 'definition': 'a sense of personal control or the ability to make meaningful choices about your own situation', 'example': 'Involving teenagers in setting household rules gives them a sense of agency and makes them more likely to follow them.', 'type': 'noun'}
    ]
  },
  {
    'id': 564,
    'answer': 'Recognizing that a habit is affecting your relationships and your wellbeing is already a significant step, and the fact that you have tried to cut back means you already understand the problem — what you need now are more structured strategies. One of the most effective tools is your phone\'s built-in screen time management: set daily limits on specific apps, and when the limit is reached, the app locks and you are forced to make a deliberate choice rather than continuing on autopilot. It also helps to schedule phone-free periods — during meals, in the first hour after waking, and the hour before bed — so your nervous system gets regular breaks from the constant stimulation these platforms are designed to deliver. The comparison you feel is not incidental; social media platforms are intentionally designed to surface emotionally activating content, so unfollowing accounts that consistently leave you feeling inadequate is both practical and evidence-based. If the anxiety you feel when you cannot check your phone is significant, it is worth speaking with a counsellor, because compulsive checking often signals that scrolling has become a way of avoiding discomfort, and addressing that underlying pattern is more durable than willpower alone. Rebuilding presence with the people around you starts with small, consistent commitments — one phone-free meal a day is a realistic first goal, and most people find those moments more genuinely fulfilling than anything they find on a feed.',
    'vocab': [
      {'word': 'deliberate', 'definition': 'done consciously and on purpose, rather than out of habit or without thinking', 'example': 'She made a deliberate decision to leave her phone in another room during dinner each evening.', 'type': 'adjective'},
      {'word': 'stimulation', 'definition': 'the process of exciting interest, alertness, or activity in the mind or body', 'example': 'Constant stimulation from notifications can make it difficult for the brain to relax or focus deeply.', 'type': 'noun'},
      {'word': 'surface', 'definition': 'to cause something to appear or become visible, especially content shown by an algorithm or platform', 'example': 'The app is designed to surface posts that trigger strong emotional reactions, keeping users engaged longer.', 'type': 'verb'},
      {'word': 'inadequate', 'definition': 'feeling that you are not good enough, especially when comparing yourself to others', 'example': 'Scrolling through highlight reels of other people\'s lives often leaves users feeling inadequate about their own.', 'type': 'adjective'},
      {'word': 'compulsive', 'definition': 'driven by a strong urge that is difficult to control, often continuing despite negative consequences', 'example': 'His compulsive need to check his phone every few minutes was interfering with his ability to concentrate at work.', 'type': 'adjective'},
      {'word': 'durable', 'definition': 'lasting and able to hold up over time, especially for habits or solutions that need to work long-term', 'example': 'Building a durable routine requires gradual changes rather than drastic restrictions that are hard to maintain.', 'type': 'adjective'}
    ]
  },
  {
    'id': 565,
    'answer': 'Helping an older parent navigate technology takes a different kind of patience than most technical support, and the most important principle is to simplify before you teach. Rather than walking through every feature at once, identify the one or two tasks that matter most to her — video calls with family are usually the priority — and repeat those steps in short, low-pressure sessions until they become habit; repetition over several visits is more effective than one exhaustive tutorial. Simplify her phone setup by removing unused apps, enlarging the font size, and placing her most-used contacts as large icons on the home screen so that she is not overwhelmed by irrelevant options every time she picks up the device. To reduce her vulnerability to scam calls, enable a call-blocking app or ask her mobile carrier about their built-in spam filtering, and teach her one clear rule: never give personal information to anyone who contacts her unexpectedly, regardless of how official they sound. Many public libraries and community centres across Canada offer free digital literacy programs specifically designed for seniors, and learning from a neutral instructor in a group setting is often less frustrating than receiving help from a family member. Reassure her that struggling with these tools is entirely normal and does not reflect on her abilities — consistent encouragement, not correction, is what will keep her motivated to try.',
    'vocab': [
      {'word': 'navigate', 'definition': 'to find your way through something complex or unfamiliar, such as technology, a system, or a difficult situation', 'example': 'Many newcomers find it challenging to navigate the Canadian healthcare system without guidance.', 'type': 'verb'},
      {'word': 'low-pressure', 'definition': 'calm, relaxed, and free from stress or urgency, especially describing a learning or social environment', 'example': 'She preferred to practise her English in low-pressure conversations with friends rather than in formal classes.', 'type': 'adjective'},
      {'word': 'overwhelmed', 'definition': 'feeling unable to cope because there is too much information, activity, or responsibility to manage at once', 'example': 'He felt overwhelmed by the number of menu options and gave up trying to use the new app.', 'type': 'adjective'},
      {'word': 'vulnerability', 'definition': 'the state of being exposed to the possibility of harm or easy to take advantage of', 'example': 'Older adults who live alone can have a higher vulnerability to phone and email scams.', 'type': 'noun'},
      {'word': 'digital literacy', 'definition': 'the ability to use digital technology effectively, safely, and with an understanding of its risks and benefits', 'example': 'Improving digital literacy among seniors can help them stay connected and avoid online fraud.', 'type': 'noun phrase'},
      {'word': 'neutral', 'definition': 'not personally connected to a situation, allowing for a more objective and less emotionally charged interaction', 'example': 'Having a neutral instructor explain the process removed the tension that often arose when her son tried to help.', 'type': 'adjective'},
      {'word': 'reassure', 'definition': 'to say or do something that removes someone\'s doubts, fears, or worries', 'example': 'The doctor reassured the patient that the side effects were temporary and would pass within a few days.', 'type': 'verb'}
    ]
  },
  {
    'id': 566,
    'answer': 'Your concern about data collection is well-founded — companies do collect significant amounts of personal information — but a handful of targeted steps can meaningfully reduce your exposure without requiring you to go offline. Start by auditing the permissions on your phone: go to your settings, review what access each app has been granted, and revoke location, microphone, and camera access for any app that does not have a clear, functional reason to need it. Enable two-factor authentication on your most important accounts — email, banking, and any account linked to a payment method — because this single step significantly reduces the risk of unauthorized access even if your password is ever compromised. In your browser, consider installing a reputable tracker blocker, which limits the amount of behavioural data that advertising networks can collect about your browsing habits across different websites. Accepting that total privacy is not achievable is actually a useful starting point, because it shifts the goal from an impossible standard to a proportionate one: reducing your exposure in the areas that carry the highest real-world risk. Being intentional about what you post publicly — rather than sharing everything by default — is ultimately the most effective long-term habit you can build.',
    'vocab': [
      {'word': 'well-founded', 'definition': 'based on solid evidence or sound reasoning, making it justified and reasonable', 'example': 'Her concern about the contract terms was well-founded — the clause had caused disputes for other clients.', 'type': 'adjective'},
      {'word': 'auditing', 'definition': 'carefully reviewing and examining something to identify what is present, unnecessary, or problematic', 'example': 'He spent an afternoon auditing all the apps on his phone and deleted those he had not used in months.', 'type': 'verb'},
      {'word': 'revoke', 'definition': 'to officially cancel or withdraw a permission or right that was previously granted', 'example': 'You can revoke an app\'s access to your location at any time through your phone\'s privacy settings.', 'type': 'verb'},
      {'word': 'two-factor authentication', 'definition': 'a security method that requires two separate steps to verify your identity before allowing access to an account', 'example': 'Since enabling two-factor authentication, she feels much more confident that her email account is secure.', 'type': 'noun phrase'},
      {'word': 'reputable', 'definition': 'having a good reputation and generally regarded as reliable and trustworthy', 'example': 'Only download security software from a reputable provider to avoid accidentally installing malware.', 'type': 'adjective'},
      {'word': 'behavioural data', 'definition': 'information collected about a person\'s online actions and habits, such as what they search, click, or purchase', 'example': 'Advertisers use behavioural data to show you products based on your browsing history and past purchases.', 'type': 'noun phrase'},
      {'word': 'proportionate', 'definition': 'appropriate and balanced in relation to the actual size or seriousness of a situation', 'example': 'A proportionate response to a minor privacy risk is adjusting your settings, not deleting all your accounts.', 'type': 'adjective'}
    ]
  },
  {
    'id': 567,
    'answer': 'The difficulty in switching off from work is one of the most widespread consequences of remote work, and it rarely improves without a sustained and deliberate effort to create boundaries where the physical separation of an office once did that work automatically. The most important step is to set a firm end-of-work time and treat it as a non-negotiable commitment: close your work applications, mute all work-related notifications, and physically put your laptop out of sight — the visual absence of the device helps signal to your brain that work is over. It is also worth having a calm, direct conversation with your manager about after-hours contact: clearly stating your availability hours is a professional communication, and most reasonable managers will adjust once they understand the impact of late messaging on your ability to recover and perform well the following day. If your workplace culture consistently rewards being always reachable, this is worth raising formally with HR as a workload and well-being concern, because chronic overwork leads to burnout, which ultimately costs the organization more than it gains from constant availability. Creating a brief transition ritual between your last work task and your personal time — a short walk, preparing a meal, or even just changing out of work clothes — helps your mind shift out of work mode in a way that checking one more email never will. Protecting your personal time is not laziness; it is the foundation of sustainable performance.',
    'vocab': [
      {'word': 'sustained', 'definition': 'continuing steadily over a long period without stopping or weakening', 'example': 'Improving your writing skills requires sustained practice over several months, not just a single workshop.', 'type': 'adjective'},
      {'word': 'non-negotiable', 'definition': 'not open to discussion or compromise; absolutely fixed and must be respected', 'example': 'Picking up the children by four o\'clock was a non-negotiable commitment she could not move around.', 'type': 'adjective'},
      {'word': 'mute', 'definition': 'to silence the sounds or notifications from a device or application', 'example': 'She mutes all work notifications after seven in the evening so that her evenings are not interrupted.', 'type': 'verb'},
      {'word': 'chronic', 'definition': 'persisting for a long time and difficult to resolve; used to describe ongoing problems rather than temporary ones', 'example': 'Chronic stress from being constantly reachable can lead to serious health problems over time.', 'type': 'adjective'},
      {'word': 'burnout', 'definition': 'a state of physical and emotional exhaustion caused by prolonged stress, especially from work', 'example': 'After working sixty-hour weeks for two years, she experienced burnout and needed three months to recover.', 'type': 'noun'},
      {'word': 'transition ritual', 'definition': 'a deliberate routine used to mark the end of one activity and the beginning of another, helping the mind shift focus', 'example': 'His transition ritual of a twenty-minute walk after closing his laptop helped him mentally leave work behind each evening.', 'type': 'noun phrase'},
      {'word': 'sustainable', 'definition': 'able to be maintained over a long period without causing harm, exhaustion, or decline in quality', 'example': 'Working at a sustainable pace may feel slower in the short term, but it produces better results over a full career.', 'type': 'adjective'}
    ]
  },
  {
    'id': 568,
    'answer': 'Discovering that your identity has been stolen is alarming, but there is a clear sequence of steps you can take right now to limit the damage and begin the process of recovery. File a police report as soon as possible — the report number is required by most financial institutions and credit bureaus before they will formally open an investigation or remove fraudulent entries from your file. Contact both Equifax Canada and TransUnion Canada to place a fraud alert on your credit file; this notifies any creditor who checks your credit that they must take additional steps to verify identity before approving new accounts. Write formally to the credit card company that issued the unauthorized account and dispute all fraudulent charges — under Canadian consumer protection guidelines, you are not liable for debts incurred through identity theft when reported correctly and promptly. Pull a full copy of your credit report from both bureaus and review every entry carefully for accounts or inquiries you do not recognize, because thieves who obtain your information often make multiple attempts across different lenders. Rebuilding your credit after this takes time, but once the fraudulent entries are disputed and documented, your score will recover — and going through this process tends to leave people with significantly stronger financial security habits than they had before.',
    'vocab': [
      {'word': 'fraudulent', 'definition': 'based on deliberate deception, intended to gain something dishonestly or illegally', 'example': 'The bank confirmed that the charge was fraudulent and began an investigation into how the card details were obtained.', 'type': 'adjective'},
      {'word': 'fraud alert', 'definition': 'a notice placed on a credit file that warns lenders to verify your identity before approving any new credit in your name', 'example': 'Placing a fraud alert is one of the first steps recommended after discovering that your personal information has been stolen.', 'type': 'noun phrase'},
      {'word': 'creditor', 'definition': 'a person or institution to whom money is owed, especially one that has issued a loan or line of credit', 'example': 'She contacted each creditor individually to explain the situation and provide the police report number.', 'type': 'noun'},
      {'word': 'liable', 'definition': 'legally responsible for something, especially a financial debt or damages', 'example': 'The lawyer confirmed that he was not liable for the debt because he had reported the theft immediately.', 'type': 'adjective'},
      {'word': 'incurred', 'definition': 'brought upon oneself, usually referring to costs, debts, or consequences that accumulated over time', 'example': 'She disputed all charges incurred after the date her card was reported stolen.', 'type': 'verb'},
      {'word': 'inquiries', 'definition': 'requests made to a credit bureau to check a person\'s credit file, which appear as a record on the report', 'example': 'Several unfamiliar inquiries on his credit report suggested that someone had been trying to apply for credit in his name.', 'type': 'noun'}
    ]
  },
  {
    'id': 569,
    'answer': 'Your concern is completely valid, and the most effective approach with a teenager is to frame this as a safety conversation rather than a rules conversation — the framing makes a real difference in whether they engage or shut down. Rather than listing what they cannot do, try sitting down together and searching their name and school name online to show them concretely what a stranger can find out about them from their posts alone — seeing it visually tends to be more persuasive than any verbal warning. Walk through specific, realistic risks: predatory adults regularly piece together location, school name, and daily routine from social media; oversharing identifiable details also creates a digital footprint that follows them into university applications and job searches years from now. Agree together on a set of reasonable precautions — turning off location tagging, setting personal accounts to private, and avoiding posts that include their school name or home neighbourhood — framed as choices they are making rather than restrictions being imposed on them. When they point out that their friends do the same thing, acknowledge it honestly without giving in: peer behaviour does not reduce the risk, and part of growing up is learning to think critically about what is normal versus what is actually safe. Teenagers are far more likely to maintain privacy habits they helped design than ones imposed on them, so involving them in setting the boundaries is the most effective long-term strategy.',
    'vocab': [
      {'word': 'concretely', 'definition': 'in a specific, tangible way that is easy to understand through real examples or visible evidence', 'example': 'Instead of describing the risk in abstract terms, she demonstrated it concretely by showing him his own address in a search result.', 'type': 'adverb'},
      {'word': 'predatory', 'definition': 'seeking to exploit or take advantage of others, especially those who are younger or more vulnerable', 'example': 'The online safety workshop explained how predatory adults use social media to identify and approach teenagers.', 'type': 'adjective'},
      {'word': 'piece together', 'definition': 'to gradually gather and combine separate pieces of information to form a complete picture', 'example': 'From a few public posts, a stranger could piece together where the child went to school and what route they took home.', 'type': 'verb phrase'},
      {'word': 'identifiable', 'definition': 'able to be recognized or traced back to a specific person based on the information available', 'example': 'Photos that include school uniforms or street signs make a child easily identifiable to anyone who views them.', 'type': 'adjective'},
      {'word': 'digital footprint', 'definition': 'the permanent record of a person\'s online activity, including posts, comments, and interactions that can be found by others', 'example': 'She reminded her students that their digital footprint would still be visible to future employers a decade from now.', 'type': 'noun phrase'},
      {'word': 'precaution', 'definition': 'a careful action taken in advance to prevent or reduce the risk of a potential problem', 'example': 'Setting your account to private is a simple precaution that significantly reduces unwanted attention online.', 'type': 'noun'}
    ]
  },
  {
    'id': 570,
    'answer': 'Taking action now is the right instinct — most employers do conduct an online search before interviews, and having a few weeks to prepare puts you in a much stronger position than you might think. Start with a thorough self-audit: search your own name as a prospective employer would, go through every public-facing profile, and note anything that could raise concerns — politically charged comments, unprofessional photos, or opinions you have since moved away from. For content you are uncomfortable with but not ready to delete, tighten the privacy settings so it is only visible to connections; for anything you genuinely regret posting, remove it outright — that is always the cleaner option. At the same time, use this moment to strengthen your professional presence: update your LinkedIn profile to reflect your current direction, fill out your summary with specifics, and engage with a few posts in your field so there is something positive and relevant for an employer to find. If an interviewer does raise something from your past activity, a measured and honest response serves you far better than denial — saying that your perspective has evolved and pointing to more recent work or experience demonstrates maturity and self-awareness, which most employers value highly. Think of cleaning up your digital presence not as emergency damage control, but as the start of a long-term habit of being intentional about how you represent yourself online.',
    'vocab': [
      {'word': 'self-audit', 'definition': 'a personal review of your own information, profiles, or practices to identify what needs to be updated or removed', 'example': 'Before applying for jobs, he did a self-audit of all his social media accounts and deleted anything that looked unprofessional.', 'type': 'noun'},
      {'word': 'public-facing', 'definition': 'visible to or intended for the general public rather than a limited or private audience', 'example': 'Make sure your public-facing LinkedIn profile reflects the professional image you want employers to see.', 'type': 'adjective'},
      {'word': 'politically charged', 'definition': 'relating to strong or controversial political opinions that are likely to provoke strong reactions or disagreement', 'example': 'She removed several politically charged posts after realizing they might affect how potential employers viewed her.', 'type': 'adjective'},
      {'word': 'outright', 'definition': 'completely and without qualification; used to emphasize that something is done fully rather than partially', 'example': 'If a post could seriously damage your reputation, it is better to remove it outright than to simply hide it.', 'type': 'adverb'},
      {'word': 'measured', 'definition': 'carefully considered and controlled in tone, especially when responding to a difficult or sensitive situation', 'example': 'Her measured response to the tough interview question impressed the panel and showed she could stay calm under pressure.', 'type': 'adjective'},
      {'word': 'maturity', 'definition': 'the quality of behaving in a sensible, responsible, and emotionally balanced way, especially in challenging situations', 'example': 'Acknowledging past mistakes with honesty is a sign of maturity that most employers genuinely respect.', 'type': 'noun'},
      {'word': 'self-awareness', 'definition': 'a clear understanding of your own thoughts, feelings, strengths, and weaknesses', 'example': 'Strong self-awareness helped him recognize that his tendency to interrupt others in meetings was damaging his reputation.', 'type': 'noun'}
    ]
  }
]

conn = sqlite3.connect(DB_PATH)
now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
updated = 0
for item in answers:
    conn.execute(
        'UPDATE template_answers SET answer=?, vocabulary=?, updated_at=? WHERE id=?',
        (item['answer'], json.dumps(item['vocab']), now, item['id'])
    )
    updated += 1

conn.commit()
conn.close()
print(f'Done — {updated} records updated.')

# Verify
conn = sqlite3.connect(DB_PATH)
remaining = conn.execute(
    "SELECT COUNT(*) FROM template_answers WHERE answer = '' AND freq_priority <= 2"
).fetchone()[0]
conn.close()
print(f'High-priority records still missing answers: {remaining}')
