import sqlite3, json
from datetime import datetime

DB_PATH = 'data/celpip_practice.db'

answers = [
  {
    'id': 596,
    'answer': 'A six-hour daily commute is genuinely unsustainable, and the fact that your health is already suffering after two years means the situation has moved well beyond a minor inconvenience into something that needs to be resolved. The first thing worth exploring is whether your employer would consider a hybrid or fully remote arrangement — many Canadian workplaces shifted toward flexible work after the pandemic, and a direct conversation about your commuting situation may be more productive than you expect. If remote work is not an option, then the honest calculation is whether the salary and career value of this particular job outweighs the cost of living closer to work; in many cases, the money saved in time, transit fares, and health-related expenses can offset a higher rent more than people realize. If neither of these is viable right now, begin a parallel job search in your own area — not as a defeat, but as a pragmatic decision to protect your health and your family relationships, both of which are harder to recover once damaged. While you are working through those longer-term options, small adjustments can help in the short term: using commute time productively for audiobooks, language practice, or even rest can reduce the psychological toll of the travel. You deserve a life that exists outside of work, and no job — however good — is worth the long-term damage that this level of exhaustion causes.',
    'vocab': [
      {'word': 'unsustainable', 'definition': 'impossible to maintain at the current level without causing harm or eventual breakdown', 'example': 'Working fourteen-hour days is unsustainable and will eventually lead to serious health problems.', 'type': 'adjective'},
      {'word': 'hybrid arrangement', 'definition': 'a work setup that combines remote and in-office days rather than requiring full attendance in either setting', 'example': 'After negotiations, her employer agreed to a hybrid arrangement of three days in the office and two at home.', 'type': 'noun phrase'},
      {'word': 'offset', 'definition': 'to balance out or compensate for a cost, loss, or disadvantage with a gain elsewhere', 'example': 'The savings on fuel and parking helped offset the higher cost of living closer to downtown.', 'type': 'verb'},
      {'word': 'pragmatic', 'definition': 'focused on practical outcomes and realistic solutions rather than ideal or emotional considerations', 'example': 'A pragmatic approach to the situation meant accepting a lower salary in exchange for shorter hours and less stress.', 'type': 'adjective'},
      {'word': 'psychological toll', 'definition': 'the mental and emotional cost or damage caused by ongoing stress, pressure, or difficult circumstances', 'example': 'The psychological toll of working in a hostile environment was greater than any financial compensation could address.', 'type': 'noun phrase'}
    ]
  },
  {
    'id': 597,
    'answer': 'Buying your first car feels overwhelming precisely because there are so many variables, but starting with your budget and actual needs — before looking at any specific vehicles — makes every other decision much easier. Decide first what you can realistically afford each month if financing, or what your upper limit is if paying outright, and then research whether a reliable used vehicle fits that budget better than a new car or a lease — for most first-time buyers, a certified pre-owned vehicle from a reputable dealer offers the best balance of reliability and cost. Before visiting any dealership, spend time on resources like the Canadian Black Book and CarGurus to understand the fair market value of the models you are considering; walking in with that knowledge significantly reduces your vulnerability to overpricing. When you have found a specific used vehicle you like, always pay for an independent pre-purchase inspection from a trusted mechanic before signing anything — this single step can save you thousands of dollars by identifying hidden problems. Approach the negotiation calmly and remember that dealers expect to negotiate; the asking price is rarely the final price, and being willing to walk away is your strongest leverage. You do not need to be a car expert to make a smart purchase — you just need to do your research and take your time.',
    'vocab': [
      {'word': 'certified pre-owned', 'definition': 'describing a used vehicle that has been inspected, reconditioned, and backed by a warranty from a manufacturer or authorized dealer', 'example': 'She chose a certified pre-owned sedan because it came with a warranty and a detailed inspection report.', 'type': 'adjective'},
      {'word': 'fair market value', 'definition': 'the price that a knowledgeable buyer would reasonably pay for something in the current market', 'example': 'Knowing the fair market value of the car before visiting the dealership gave him the confidence to negotiate.', 'type': 'noun phrase'},
      {'word': 'pre-purchase inspection', 'definition': 'an evaluation of a used vehicle conducted by an independent mechanic before the buyer commits to purchasing it', 'example': 'The pre-purchase inspection revealed a cracked frame that was not visible from the outside, saving her from a costly mistake.', 'type': 'noun phrase'},
      {'word': 'leverage', 'definition': 'the power or advantage that gives you a stronger position in a negotiation or situation', 'example': 'Having three competing quotes gave him real leverage when he sat down with the final dealer.', 'type': 'noun'},
      {'word': 'vulnerability', 'definition': 'the state of being at risk of being taken advantage of, especially when you lack relevant knowledge or experience', 'example': 'Going into the dealership unprepared increases your vulnerability to high-pressure sales tactics.', 'type': 'noun'}
    ]
  },
  {
    'id': 598,
    'answer': 'This is one of the more complex financial decisions for urban Canadians, and the right answer depends almost entirely on the specifics of your situation rather than a general rule. Start by calculating the true annual cost of car ownership in your area — insurance alone for a new driver in cities like Toronto or Vancouver can exceed three thousand dollars per year, and when you add financing, fuel, parking, and maintenance, the total often surpasses ten thousand annually — then compare that honestly against what you currently spend on transit plus the real value of the time you would save. If your commute on transit is unreliable in ways that genuinely put your job at risk or prevent you from reaching important appointments, that is a strong practical argument for a vehicle, because time and job security have real monetary value. A middle-ground option worth considering is a vehicle used selectively: some people find that a modest, fuel-efficient used car combined with transit for shorter trips gives them the flexibility they need without the full cost burden. You might also explore whether a car-sharing service like Communauto or ZipCar makes sense as a bridge — it lets you access a vehicle when you genuinely need one without the fixed expenses of ownership. The decision ultimately comes down to what combination of cost, convenience, and flexibility fits your income and your daily reality.',
    'vocab': [
      {'word': 'surpasses', 'definition': 'exceeds or goes beyond a particular amount, level, or standard', 'example': 'The total annual cost of car ownership frequently surpasses what people initially budget for.', 'type': 'verb'},
      {'word': 'monetary value', 'definition': 'the worth of something expressed in financial or economic terms', 'example': 'Time saved on a commute has real monetary value when you calculate what it allows you to do instead.', 'type': 'noun phrase'},
      {'word': 'fuel-efficient', 'definition': 'using a relatively small amount of fuel per distance travelled, resulting in lower running costs', 'example': 'She chose a fuel-efficient hatchback to keep her monthly driving costs as low as possible.', 'type': 'adjective'},
      {'word': 'cost burden', 'definition': 'the weight of ongoing financial obligations associated with owning or maintaining something', 'example': 'Leasing rather than buying can reduce the immediate cost burden, though it does not build equity.', 'type': 'noun phrase'},
      {'word': 'bridge', 'definition': 'a temporary solution that helps you manage while you move toward a longer-term arrangement', 'example': 'Using a car-sharing service was a useful bridge while she saved up for a down payment on her own vehicle.', 'type': 'noun'}
    ]
  },
  {
    'id': 599,
    'answer': 'Learning to drive at 35 after years of managing without it takes real courage, and the anxiety you feel is far more common among adult learners than most people admit — it does not mean you cannot succeed. The most important immediate change is to find an instructor who has specific experience working with anxious adult learners; your current instructor\'s impatience is almost certainly making your anxiety worse, not better, and the right match at this stage makes an enormous difference. Look for a driving school that explicitly markets to nervous or mature learners — these instructors are trained to build confidence incrementally, avoid reactive commentary during lessons, and pace the experience to the learner rather than to a fixed schedule. Outside of lessons, spending time as a passenger and consciously observing traffic patterns, signage, and road behaviour can build familiarity in a lower-stakes way before you are behind the wheel. If your anxiety is severe enough to cause panic during lessons, a few sessions with a counsellor who works with performance anxiety can be highly effective — cognitive-behavioural techniques are specifically designed to interrupt the physical cycle of fear that makes driving feel impossible. Many people who started exactly where you are — dependent, anxious, and doubting themselves — are now confident everyday drivers, and the independence you gain on the other side of this process is absolutely worth the discomfort of getting there.',
    'vocab': [
      {'word': 'incrementally', 'definition': 'gradually and in small stages rather than all at once', 'example': 'A good instructor builds a nervous learner\'s confidence incrementally, starting with quiet roads before moving to busy intersections.', 'type': 'adverb'},
      {'word': 'reactive commentary', 'definition': 'critical or alarmed remarks made in immediate response to a learner\'s actions, which tend to increase rather than reduce anxiety', 'example': 'Her previous instructor\'s reactive commentary made her freeze at every intersection instead of building her confidence.', 'type': 'noun phrase'},
      {'word': 'performance anxiety', 'definition': 'fear or nervousness specifically triggered by having to perform a task or skill, often making it harder to do', 'example': 'He experienced performance anxiety during his driving test even though he drove perfectly in practice sessions.', 'type': 'noun phrase'},
      {'word': 'cognitive-behavioural', 'definition': 'relating to a therapy approach that targets unhelpful thinking patterns and the behaviours they produce', 'example': 'She found cognitive-behavioural techniques helpful for managing the intrusive thoughts that appeared whenever she got behind the wheel.', 'type': 'adjective'},
      {'word': 'lower-stakes', 'definition': 'involving less pressure, risk, or consequence compared to the main activity being prepared for', 'example': 'Practising parallel parking in an empty car park is a lower-stakes way to build the skill before trying it on a busy street.', 'type': 'adjective'}
    ]
  },
  {
    'id': 600,
    'answer': 'Insurance disputes after an accident are genuinely stressful, and the most important thing you can do right now is to be organized and persistent, because the process tends to favour whoever keeps the most thorough records. Gather every piece of evidence related to the accident: photos of the damage and the scene, the police report number, witness contact information, and a written account of exactly what happened while it is still fresh — this documentation is your foundation for any dispute about fault. When dealing with the other driver\'s insurer, remember that their adjuster works for that company, not for you; you are not obligated to accept their initial fault assessment, and you have the right to formally challenge their determination in writing. If your own insurer is being unhelpful, ask to escalate your file to a senior adjuster and put all future communication in writing — a paper trail creates accountability and changes the tone of the process. If the dispute stalls or the amounts involved are significant, a consultation with a personal injury or insurance lawyer can clarify your rights quickly; many work on contingency for accident claims, meaning there is no upfront cost. While this is unresolved, keep all rental receipts and any other out-of-pocket expenses carefully documented, as these can be recovered as part of a settlement.',
    'vocab': [
      {'word': 'adjuster', 'definition': 'an insurance professional who investigates claims, assesses damage, and determines how much the insurer will pay', 'example': 'The adjuster visited the repair shop to assess the damage before the insurer approved the claim.', 'type': 'noun'},
      {'word': 'fault determination', 'definition': 'the official process of deciding which driver is legally responsible for causing an accident', 'example': 'She disputed the fault determination because the police report supported a different account of how the collision occurred.', 'type': 'noun phrase'},
      {'word': 'paper trail', 'definition': 'a series of written records that serve as evidence of communications, decisions, or transactions', 'example': 'Sending all requests by email rather than phone created a paper trail that proved useful when the dispute went to arbitration.', 'type': 'noun phrase'},
      {'word': 'contingency', 'definition': 'a fee arrangement where a lawyer is paid only if they win the case, taking a percentage of the settlement rather than charging upfront', 'example': 'Because the lawyer worked on contingency, the client did not need any money upfront to pursue the claim.', 'type': 'noun'},
      {'word': 'settlement', 'definition': 'a formal agreement to resolve a dispute by paying an agreed amount, usually without going to court', 'example': 'Both parties reached a settlement that covered the repair costs and the rental car expenses incurred during the dispute.', 'type': 'noun'}
    ]
  },
  {
    'id': 601,
    'answer': 'This is one of the most difficult conversations adult children face, and approaching it with concern for both your father\'s safety and his sense of dignity gives you the best chance of making progress without permanently damaging your relationship. Rather than making it a direct confrontation between the two of you, consider involving his family doctor first — a physician raising the concern carries far more authority and feels less personal, and many doctors will address driving fitness directly if the family brings it to their attention. Another route is to request a formal driving assessment through a rehabilitation centre or occupational therapist; in Canada, these assessments are specifically designed for this situation and produce an objective, third-party verdict that removes the decision from the family dynamic entirely. When you do speak with him, acknowledge honestly what his car represents — independence, identity, and the ability to participate in his own life — and come with concrete alternatives already researched: Wheel-Trans services, Uber, or community volunteer driver programs can significantly ease the loss of that independence. If he continues to refuse and you remain genuinely concerned, you have both a legal and moral obligation to report your concerns to the provincial licensing authority, which can require a formal reassessment; this is not a betrayal but a responsible act of care for him and for others on the road. The goal is not to diminish his autonomy but to keep everyone safe, and framing every conversation around that shared goal — with patience and without anger — remains your strongest approach.',
    'vocab': [
      {'word': 'occupational therapist', 'definition': 'a health professional who assesses and supports a person\'s ability to perform daily activities, including driving evaluations for older adults', 'example': 'The occupational therapist conducted a formal driving assessment and recommended that he surrender his licence.', 'type': 'noun phrase'},
      {'word': 'third-party verdict', 'definition': 'an official judgment or decision made by someone independent of the people directly involved in a dispute', 'example': 'Having a third-party verdict from a certified assessor made the conversation far less emotionally charged for the whole family.', 'type': 'noun phrase'},
      {'word': 'licensing authority', 'definition': 'the government body responsible for issuing, monitoring, and revoking driver\'s licences', 'example': 'She reported her concerns to the provincial licensing authority, which then required her father to complete a medical review.', 'type': 'noun phrase'},
      {'word': 'autonomy', 'definition': 'the right and ability to make your own decisions and live independently, without being controlled by others', 'example': 'Preserving her mother\'s sense of autonomy was as important as ensuring her physical safety.', 'type': 'noun'},
      {'word': 'rehabilitation centre', 'definition': 'a facility providing assessment and therapy to help people maintain or recover physical, cognitive, or functional abilities', 'example': 'The rehabilitation centre offered a standardized driving evaluation that measured reaction time and decision-making on the road.', 'type': 'noun phrase'}
    ]
  },
  {
    'id': 602,
    'answer': 'Spending three thousand dollars on repairs in a single year on a car that is still unreliable is a clear signal that you have moved past the point where continued repairs make financial sense. Your first step is to get a comprehensive assessment from a trusted mechanic — ideally not the same shop that has been doing the work — to find out what the vehicle will realistically need over the next twelve months; if those projected costs approach or exceed the car\'s current market value, replacement is the rational choice even when it feels unaffordable. On the financing side, many Canadians are surprised to find that a modest, reliable used vehicle through a bank loan or credit union can result in monthly payments that are lower than their recent repair bills, especially once you factor in the hidden costs of breakdowns: missed work, emergency towing, and short-notice rental cars. Before making any decision, explore whether your workplace can offer any short-term flexibility — remote days or adjusted hours — while you sort out your transportation situation. If purchasing is genuinely not possible right now, a local car-sharing program or a lease-to-own arrangement through a smaller dealer may offer a workable middle path. The emotional toll of unreliable transportation is real, and treating this as a solvable financial problem rather than a situation to simply endure is the mindset that will move you forward.',
    'vocab': [
      {'word': 'comprehensive assessment', 'definition': 'a thorough evaluation that examines all relevant aspects of something, not just the most visible or immediate issue', 'example': 'A comprehensive assessment of the vehicle revealed several problems the previous mechanic had not mentioned.', 'type': 'noun phrase'},
      {'word': 'projected costs', 'definition': 'estimated future expenses calculated based on current information, trends, and known upcoming needs', 'example': 'The mechanic provided a list of projected costs for the next year, which made the decision to sell the car much clearer.', 'type': 'noun phrase'},
      {'word': 'rational', 'definition': 'based on clear reasoning and practical evidence rather than emotion or habit', 'example': 'It is rational to replace a vehicle when repair costs consistently exceed its market value.', 'type': 'adjective'},
      {'word': 'lease-to-own', 'definition': 'a financial arrangement where regular payments gradually lead to ownership of the item, combining aspects of renting and buying', 'example': 'The lease-to-own option allowed him to drive a reliable car immediately while spreading the cost over two years.', 'type': 'adjective'},
      {'word': 'endure', 'definition': 'to continue putting up with something difficult or unpleasant without resolving the underlying cause', 'example': 'She had been enduring the stress of an unreliable car for months before finally deciding to replace it.', 'type': 'verb'}
    ]
  },
  {
    'id': 603,
    'answer': 'What you are describing — avoidance, panic responses, and a significant change in your ability to function after a traumatic event — is a recognized psychological response to trauma, and it is both more common among drivers than most people realize and genuinely treatable. The most effective approach is to work with a therapist who specializes in trauma or anxiety, particularly one who uses cognitive-behavioural therapy or EMDR, both of which have strong evidence for reducing post-accident driving fear; attempting to push through the anxiety by willpower alone often reinforces it rather than reducing it. Alongside therapy, a gradual and structured return to driving — where you start with very short, low-stakes trips in familiar areas with little traffic and build up distance and complexity only as your comfort increases — is far more effective than either complete avoidance or forcing yourself onto a highway before you are ready. It is also worth speaking to your doctor, because anxiety of this severity can sometimes benefit from short-term medication support while you work through the psychological dimension in therapy. Losing confidence after a serious accident is not a character flaw or a sign of permanent limitation — it is a predictable response to a frightening experience. With the right professional support and a patient, graduated approach, the vast majority of people in your situation do return to driving with full confidence.',
    'vocab': [
      {'word': 'post-accident', 'definition': 'occurring after a vehicle collision, especially used to describe psychological or behavioural changes that follow the event', 'example': 'Her post-accident anxiety was so severe that she avoided even riding as a passenger for several weeks.', 'type': 'adjective'},
      {'word': 'EMDR', 'definition': 'Eye Movement Desensitization and Reprocessing; a structured therapy technique used to reduce the emotional intensity of traumatic memories', 'example': 'After several sessions of EMDR, he found that the memory of the accident no longer triggered the same physical panic response.', 'type': 'noun'},
      {'word': 'reinforces', 'definition': 'makes a response, habit, or pattern stronger and more fixed by repeating the conditions that produce it', 'example': 'Avoiding the highway entirely reinforces the fear rather than helping the brain learn that the situation is manageable.', 'type': 'verb'},
      {'word': 'graduated approach', 'definition': 'a method of tackling a challenge by progressing through stages of increasing difficulty rather than attempting everything at once', 'example': 'Her therapist recommended a graduated approach to driving, beginning with five-minute trips around the block.', 'type': 'noun phrase'},
      {'word': 'avoidance', 'definition': 'the pattern of staying away from a feared situation or activity, which provides short-term relief but maintains or worsens anxiety over time', 'example': 'Avoidance of highways seemed to help at first, but over time it expanded until she was afraid to drive at all.', 'type': 'noun'}
    ]
  },
  {
    'id': 604,
    'answer': 'Insurance for new drivers in Canada is genuinely expensive, and the premiums you are being quoted are not a mistake — they reflect the statistical risk that insurers assign to drivers without an established driving record. The most effective way to reduce costs in the short term is to work with an independent broker who can compare rates across multiple insurers simultaneously, since rates for the same driver profile can vary by hundreds of dollars per year between companies. Many insurers now offer telematics programs — apps or devices that monitor your actual driving behaviour, including braking, speed, and time of day — and drivers who participate and drive safely can earn discounts of fifteen to thirty percent; if you drive cautiously and avoid late nights, these programs can substantially reduce your first-year premium. The vehicle you choose also has a significant impact: sports cars, newer models, and high-theft vehicles cost considerably more to insure, while older, modest, and domestically common vehicles carry much lower premiums. Taking an accredited defensive driving course earns a discount with many insurers and is worth completing in any case for the skill development. Once you accumulate twelve months of clean driving history, your premiums will begin to drop noticeably — the first year is the most expensive phase, and it does improve from there.',
    'vocab': [
      {'word': 'premiums', 'definition': 'the regular payments made to an insurance company in exchange for coverage', 'example': 'His annual premiums dropped significantly after he completed a year of driving without any claims or violations.', 'type': 'noun'},
      {'word': 'independent broker', 'definition': 'an insurance professional who represents multiple companies and compares options on the buyer\'s behalf rather than selling for a single insurer', 'example': 'Working with an independent broker saved her nearly four hundred dollars annually compared to going directly to one company.', 'type': 'noun phrase'},
      {'word': 'telematics', 'definition': 'technology that tracks and transmits data about driving behaviour — such as speed, braking habits, and mileage — to allow insurers to price risk more accurately', 'example': 'She enrolled in her insurer\'s telematics program and received a twenty percent discount after three months of safe driving data.', 'type': 'noun'},
      {'word': 'domestically common', 'definition': 'widely owned within the local market, making the vehicle easier and cheaper to repair and insure', 'example': 'Choosing a domestically common model meant that parts were readily available and insurance costs were significantly lower.', 'type': 'adjective'},
      {'word': 'accredited', 'definition': 'officially recognized and approved by a relevant authority or professional body as meeting a required standard', 'example': 'Completing an accredited defensive driving course reduced his annual insurance premium by eight percent.', 'type': 'adjective'}
    ]
  },
  {
    'id': 605,
    'answer': 'Cycling to work is a legitimate and widely practised commuting choice, and the concern your family expresses, while understandable, appears to be disproportionate to the actual risk you are taking based on your own experience of the route. The most productive response is not to debate whether cycling is dangerous in the abstract, but to show your family the concrete safety measures you already follow and to address any gaps that might give their concerns some validity. Make sure you are doing the things that genuinely matter statistically: wearing a properly fitted helmet every single time, using both front and rear lights even during daylight hours, following traffic laws consistently, and choosing routes with dedicated cycling infrastructure wherever possible — in many Canadian cities, the network of protected bike lanes has expanded considerably in recent years. Having a calm conversation that acknowledges their concern while also walking them through your actual routine tends to reduce anxiety far more effectively than simply dismissing their worry as overblown. At the same time, it is entirely reasonable to set a boundary: you appreciate that they care, and you take safety seriously, but this is your commute and your decision to make as a capable adult. One minor incident over a period of regular cycling is a reasonable record, and continuing a habit that benefits your health, your finances, and the environment is a defensible and worthwhile choice.',
    'vocab': [
      {'word': 'disproportionate', 'definition': 'larger, more intense, or more serious than is warranted by the actual situation', 'example': 'Their anxiety about the commute seemed disproportionate given that he had been cycling the same route safely for six months.', 'type': 'adjective'},
      {'word': 'cycling infrastructure', 'definition': 'the physical features of a city designed to support safe cycling, such as dedicated lanes, separated paths, and cycling signals', 'example': 'The expansion of cycling infrastructure in the city centre made her daily commute noticeably safer and more comfortable.', 'type': 'noun phrase'},
      {'word': 'dismissing', 'definition': 'treating a concern, idea, or opinion as not worth taking seriously or considering carefully', 'example': 'Rather than dismissing their worry entirely, he acknowledged it and explained the specific precautions he took every day.', 'type': 'verb'},
      {'word': 'statistically', 'definition': 'based on data collected across a large number of cases, rather than on individual impressions or anecdotes', 'example': 'Wearing a helmet and using lights statistically reduces the risk of serious injury while cycling significantly.', 'type': 'adverb'},
      {'word': 'legitimate', 'definition': 'valid, reasonable, and generally accepted as an appropriate choice within normal social norms or standards', 'example': 'Cycling to work is a legitimate choice that millions of Canadians make every day for health, cost, and environmental reasons.', 'type': 'adjective'}
    ]
  }
]

conn = sqlite3.connect(DB_PATH)
now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
updated = 0
for item in answers:
    conn.execute(
        'UPDATE template_answers SET answer=?, vocabulary=?, updated_at=? WHERE id=?',
        (item['answer'], json.dumps(item['vocab']), now, item['id'])
    )
    updated += 1

conn.commit()
conn.close()
print(f'Done — {updated} records updated.')

conn = sqlite3.connect(DB_PATH)
remaining = conn.execute(
    "SELECT COUNT(*) FROM template_answers WHERE answer = '' AND freq_priority <= 2"
).fetchone()[0]
conn.close()
print(f'High-priority records still missing answers: {remaining}')
